language: objective-c
osx_image: xcode7.1
script:
- set -o pipefail
- xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk macosx | xcpretty -c
- xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- xcodebuild -project URITemplate.xcodeproj -scheme URITemplate build -sdk watchos | xcpretty -c
- pod lib lint
